accounts/urls.py
from django.urls import path
from .views import SignUpView, SettingsView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('settings/', SettingsView.as_view(), name='settings'),
]

body_comp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('measurements.urls')),
]

measurements/urls.py
from django.urls import path
from .views import HomePageView, AddMeasurementView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path("add_measurement", AddMeasurementView.as_view(), name='add_measurement'),

]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

measurements/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from datetime import date


class Measurement(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    date = models.DateField(default=date.today())
    weight = models.DecimalField(max_digits=6, decimal_places=2)
    bust = models.DecimalField(max_digits=6, decimal_places=2)
    chest = models.DecimalField(max_digits=6, decimal_places=2)
    waist = models.DecimalField(max_digits=6, decimal_places=2)
    hips = models.DecimalField(max_digits=6, decimal_places=2)
    left_thigh = models.DecimalField(max_digits=6, decimal_places=2)
    right_thigh = models.DecimalField(max_digits=6, decimal_places=2)
    left_calf = models.DecimalField(max_digits=6, decimal_places=2)
    right_calf = models.DecimalField(max_digits=6, decimal_places=2)
    left_forearm = models.DecimalField(max_digits=6, decimal_places=2)
    right_forearm = models.DecimalField(max_digits=6, decimal_places=2)
    left_upper_arm = models.DecimalField(max_digits=6, decimal_places=2)
    right_upper_arm = models.DecimalField(max_digits=6, decimal_places=2)

    def __str__(self):
        return f'Body Comp from {self.date}'

    def get_absolute_url(self):
        return reverse('measurement_detail', kwargs={'pk': self.pk})

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView
from .models import CustomUser
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'registration/signup.html'


class SettingsView(LoginRequiredMixin, ListView):
    template_name = 'settings.html'
    model = CustomUser

measurements/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView
from .models import Measurement
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin


class HomePageView(LoginRequiredMixin, ListView):
    template_name = 'home.html'
    model = Measurement

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class AddMeasurementView(LoginRequiredMixin, CreateView):
    template_name = 'add_measurements.html'
    model = Measurement
    fields = ['date', 'weight', 'bust', 'chest', 'waist', 'hips', 'left_thigh', 'right_thigh', 'left_calf',
              'right_calf', 'left_forearm', 'right_forearm', 'left_upper_arm', 'right_upper_arm']
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

templates/add_measurements.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}Add A Measurement{% endblock title %}

{% block content %}

<h3>Input your most recent measurements:</h3>

<form action="" method="post">{% csrf_token %}
    {{ form|crispy }}
    <button class="button" type="submit">Submit</button>
</form>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    {% include 'navbar.html' %}

        <div class="content">
            {% block content %}
            {% endblock content %}
        </div>

    <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
            crossorigin="anonymous" defer>
    </script>
</body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}Your Measurements{% endblock title %}

{% block content %}
<table>
    <thead>
        <tr>
            <th>Date</th>
            <th>Weight</th>
            <th>Chest</th>
            <th>Bust</th>
            <th>Waist</th>
            <th>Hips</th>
            <th>Left Thigh</th>
            <th>Right Thigh</th>
            <th>Left Calf</th>
            <th>Right Calf</th>
            <th>Left Forearm</th>
            <th>Right Forearm</th>
            <th>Left Upper Arm</th>
            <th>Right Upper Arm</th>
        </tr>
    </thead>
    {% for measurement in measurement_list %}
    <tr>
        <td>{{ measurement.date }}</td>
        <td>{{ measurement.weight }}</td>
        <td>{{ measurement.bust }}</td>
        <td>{{ measurement.chest }}</td>
        <td>{{ measurement.waist }}</td>
        <td>{{ measurement.hips }}</td>
        <td>{{ measurement.left_thigh }}</td>
        <td>{{ measurement.right_thigh }}</td>
        <td>{{ measurement.left_calf }}</td>
        <td>{{ measurement.right_calf }}</td>
        <td>{{ measurement.left_forearm }}</td>
        <td>{{ measurement.right_forearm }}</td>
        <td>{{ measurement.left_upper_arm }}</td>
        <td>{{ measurement.right_upper_arm }}</td>
    </tr>
    {% endfor %}
</table>


{% endblock content %}

templates/navbar.html
    <header>
        <div class="header-left">
            <h1><a id='logo' href="{% url 'home' %}">Comp Tracker</a></h1>
        </div>
        <div class="header-right">
            {%  if user.is_authenticated %}
                <div class="dropdown">
	                <button class="button btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
		                Menu
	                </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li><a class="dropdown-item" href="{% url 'home' %}">View Measurements</a></li>
                        <li><a class="dropdown-item" href="{% url 'add_measurement' %}">Add Measurement</a></li>
                        <li><a class="dropdown-item" href="{% url 'settings' %}">User Settings</a></li>
                    </ul>
	            </div>
                <a class="button" href="{% url 'logout' %}">Log Out</a>
            {% else %}
                <a class="button" href="{% url 'login' %}">Log In</a>
                <a class="button" href="{% url 'signup' %}">Sign Up</a>
            {% endif %}

        </div>
    </header>

templates/settings.html
{% extends 'base.html' %}

{% block title %}User Settings{% endblock title %}


{% block content %}

    <div>
        <h2>Security</h2>
            <a class="button" href="{% url 'password_change' %}">Update Password</a>
    </div>

{% endblock content %}